In [1]:
#Dependencies
import os 
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#open and read csv

crimes_2017 = "Resources/crime_incident_data2017.csv"

crimes_2017 = pd.read_csv(crimes_2017)

In [3]:
crimes_2017.head()

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
0,NaN,17-X4762181,Person,NaN,1.0,1/1/96,1/1/96,800.0,Sex Offenses,1.0,Rape,NaN,NaN,NaN,NaN,1/26/17,1/1/17
1,NaN,17-X4757824,Property,Centennial,1.0,1/20/00,1/1/00,1615.0,Fraud Offenses,1.0,Identity Theft,NaN,NaN,NaN,NaN,1/20/17,1/1/17
2,200 BLOCK OF SE 78TH AVE,17-900367,Property,Montavilla,1.0,12/1/03,12/1/03,800.0,Fraud Offenses,1.0,False Pretenses/Swindle/Confidence Game,45.5207,-122.583,7668150.0,682825.0,1/9/17,1/1/17
3,NaN,17-X4748982,Property,Southwest Hills,1.0,1/1/10,1/1/10,0.0,Fraud Offenses,1.0,Identity Theft,NaN,NaN,NaN,NaN,1/5/17,1/1/17
4,NaN,17-X4748982,Property,Southwest Hills,1.0,1/1/10,1/1/10,0.0,Larceny Offenses,1.0,All Other Larceny,NaN,NaN,NaN,NaN,1/5/17,1/1/17

In [4]:
#consistency counting -- looking for missing values
crimes_2017.count()

Address              25536
Case Number          27988
Crime Against        27988
Neighborhood         27162
Number of Records    27988
Occur Date           27988
Occur Month Year     27988
Occur Time           27988
Offense Category     27988
Offense Count        27988
Offense Type         27988
Open Data Lat        25147
Open Data Lon        25147
Open Data X          25147
Open Data Y          25147
Report Date          27988
Report Month Year    27988
dtype: int64

In [5]:
#dropping null rows
clean_crime = crimes_2017.dropna(how ='any')

In [6]:
clean_crime.count()

Address              24771
Case Number          24771
Crime Against        24771
Neighborhood         24771
Number of Records    24771
Occur Date           24771
Occur Month Year     24771
Occur Time           24771
Offense Category     24771
Offense Count        24771
Offense Type         24771
Open Data Lat        24771
Open Data Lon        24771
Open Data X          24771
Open Data Y          24771
Report Date          24771
Report Month Year    24771
dtype: int64

In [7]:
crimes_2017['Offense Type']

0                                               Rape
1                                     Identity Theft
2            False Pretenses/Swindle/Confidence Game
3                                     Identity Theft
4                                  All Other Larceny
5                                     Identity Theft
6            False Pretenses/Swindle/Confidence Game
7                                     Identity Theft
8                              Credit Card/ATM Fraud
9                                     Identity Theft
10                                    Identity Theft
11                                    Identity Theft
12                                      Embezzlement
13           False Pretenses/Swindle/Confidence Game
14                                    Identity Theft
15                                    Identity Theft
16                                       Shoplifting
17                                 All Other Larceny
18                                 All Other Larceny
19                                    Identity Theft
20                                    Identity Theft
21                          Theft From Motor Vehicle
22                          Theft From Motor Vehicle
23                                 All Other Larceny
24                             Credit Card/ATM Fraud
25                                    Identity Theft
26           False Pretenses/Swindle/Confidence Game
27                                    Identity Theft
28           False Pretenses/Swindle/Confidence Game
29                                    Identity Theft
                            ...
27959                                      Vandalism
27960                                      Vandalism
27961                                      Vandalism
27962                                      Vandalism
27963                                      Vandalism
27964                                      Vandalism
27965                                      Vandalism
27966                                      Vandalism
27967                                      Vandalism
27968                       Drug/Narcotic Violations
27969                       Drug/Narcotic Violations
27970                       Drug/Narcotic Violations
27971                       Drug/Narcotic Violations
27972                                           Rape
27973                             Aggravated Assault
27974                              All Other Larceny
27975    Theft of Motor Vehicle Parts or Accessories
27976                       Theft From Motor Vehicle
27977                       Theft From Motor Vehicle
27978                            Motor Vehicle Theft
27979                              All Other Larceny
27980                            Theft From Building
27981                       Theft From Motor Vehicle
27982                       Theft From Motor Vehicle
27983                                      Vandalism
27984                              All Other Larceny
27985                            Motor Vehicle Theft
27986                                       Burglary
27987                                       Burglary
27988                                            NaN
Name: Offense Type, Length: 27989, dtype: object

In [8]:
crimes_2017['Offense Type'].unique()
#crimes_2017['Offense Category'].value_counts()

array(['Rape', 'Identity Theft',
       'False Pretenses/Swindle/Confidence Game', 'All Other Larceny',
       'Credit Card/ATM Fraud', 'Embezzlement', 'Shoplifting',
       'Theft From Motor Vehicle', 'Motor Vehicle Theft', 'Burglary',
       'Theft of Motor Vehicle Parts or Accessories',
       'Counterfeiting/Forgery', 'Intimidation', 'Vandalism',
       'Statutory Rape', 'Simple Assault', 'Theft From Building',
       'Robbery', 'Fondling', 'Aggravated Assault',
       'Theft From Coin-Operated Machine or Device',
       'Sexual Assault With An Object', 'Hacking/Computer Invasion',
       'Drug/Narcotic Violations', 'Pocket-Picking',
       'Stolen Property Offenses', 'Weapons Law Violations',
       'Purse-Snatching', 'Arson', 'Extortion/Blackmail', 'Sodomy',
       'Prostitution', 'Kidnapping/Abduction',
       'Drug Equipment Violations', 'Wire Fraud', 'Involuntary Servitude',
       'Pornography/Obscene Material', 'Commercial Sex Acts',
       'Assisting or Promoting Prostitution', 'Impersonation',
       'Murder and Non-negligent Manslaughter', 'Animal Cruelty',
       'Incest', nan], dtype=object)

In [ ]:
#crimes_2017['Report Date'].value_counts()
#crimes_2017['Report Date'].unique()

#crimes_2017['Neighborhood'].value_counts()