In [1]:
#Dependencies
import os 
import pandas as pd
import seaborn as sns
import numpy as np
import matplotlib.pyplot as plt

In [4]:
#open and read csv

crimes_2017 = "Resources/crime_incident_data2017.csv"

crimes_2017 = pd.read_csv(crimes_2017)

In [6]:
crimes_2017.head()

,Address,Case Number,Crime Against,Neighborhood,Number of Records,Occur Date,Occur Month Year,Occur Time,Offense Category,Offense Count,Offense Type,Open Data Lat,Open Data Lon,Open Data X,Open Data Y,Report Date,Report Month Year
0,NaN,17-X4762181,Person,NaN,1.0,1/1/96,1/1/96,800.0,Sex Offenses,1.0,Rape,NaN,NaN,NaN,NaN,1/26/17,1/1/17
1,NaN,17-X4757824,Property,Centennial,1.0,1/20/00,1/1/00,1615.0,Fraud Offenses,1.0,Identity Theft,NaN,NaN,NaN,NaN,1/20/17,1/1/17
2,200 BLOCK OF SE 78TH AVE,17-900367,Property,Montavilla,1.0,12/1/03,12/1/03,800.0,Fraud Offenses,1.0,False Pretenses/Swindle/Confidence Game,45.5207,-122.583,7668150.0,682825.0,1/9/17,1/1/17
3,NaN,17-X4748982,Property,Southwest Hills,1.0,1/1/10,1/1/10,0.0,Fraud Offenses,1.0,Identity Theft,NaN,NaN,NaN,NaN,1/5/17,1/1/17
4,NaN,17-X4748982,Property,Southwest Hills,1.0,1/1/10,1/1/10,0.0,Larceny Offenses,1.0,All Other Larceny,NaN,NaN,NaN,NaN,1/5/17,1/1/17